pluginId=pano-plugin-cookies
pluginName=Cookies
pluginDescription=Adds a customizable cookie consent info showing for Pano. 
pluginPanoVersion=local-build
pluginClass=com.panomc.plugins.cookies.CookiesPlugin
pluginDeveloper=Pano
pluginLicense=MIT
pluginSourceUrl=https://github.com/panomc/pano-plugin-cookies
pluginDependencies=
pluginRequires=

pf4jVersion=3.11.1
vertxVersion=4.5.7
gsonVersion=2.11.0
handlebarsVersion=4.4.0
springContextVersion=5.3.39
organization=panomc